FROM python:3

RUN apt-get update
RUN apt-get install python3 python3-venv -y
RUN useradd -M -s /bin/bash -b /srv/xmrauctions xmrauctions
COPY . /srv/xmrauctions
RUN chown -R xmrauctions:xmrauctions /srv/xmrauctions

USER xmrauctions
WORKDIR /srv/xmrauctions
RUN python3 -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt
RUN chmod +x ./bin/*

ENTRYPOINT ["./bin/entrypoint"]
