FROM docker.elastic.co/logstash/logstash:7.5.2

RUN rm -f /usr/share/logstash/pipeline/logstash.conf
RUN /usr/share/logstash/bin/logstash-plugin install logstash-output-elasticsearch

ADD files/logstash.conf /usr/share/logstash/pipeline/logstash.conf
