{
 "title": "XMR Auctions",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Requests by Method/View",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_view_transport_method_total[1m]) * 60",
     "legendFormat": "{{ method }} - {{ view }}"
    }
   ]
  },
  {
   "title": "DB Migrations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:django_migrations_applied_total:max",
     "legendFormat": "Applied"
    },
    {
     "expr": "job:django_migrations_unapplied_total:max",
     "legendFormat": "Unapplied"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum{job=\"django\"}[1m])",
     "legendFormat": "{{ method }} - {{ view }}"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(django_db_new_connections_total[1m]) * 60",
     "legendFormat": "DB Connections"
    }
   ]
  },
  {
   "title": "DB Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(django_model_updates_total{job=\"django\"}[1m]) * 60",
     "legendFormat": "{{ model }} Updates"
    },
    {
     "expr": "rate(django_model_deletes_total{job=\"django\"}[1m]) * 60",
     "legendFormat": "{{ model }} Deletes"
    },
    {
     "expr": "rate(django_model_inserts_total{job=\"django\"}[1m]) * 60",
     "legendFormat": "{{ model }} Inserts"
    }
   ]
  },
  {
   "title": "Estimated CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "{{ job }}"
    }
   ]
  }
 ]
}