# Generated by Django 2.2.7 on 2019-12-20 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_address', models.CharField(max_length=96)),
                ('escrow_account_index', models.IntegerField()),
                ('agreed_price_xmr', models.FloatField()),
                ('platform_fee_xmr', models.FloatField()),
                ('expected_payment_xmr', models.FloatField()),
                ('received_payment_xmr', models.FloatField(default=0.0)),
                ('escrow_period_days', models.PositiveSmallIntegerField(default=30)),
                ('buyer_notified', models.BooleanField(default=False)),
                ('payment_received', models.BooleanField(default=False)),
                ('seller_notified', models.BooleanField(default=False)),
                ('payment_refunded', models.BooleanField(default=False)),
                ('item_shipped', models.BooleanField(default=False)),
                ('item_received', models.BooleanField(default=False)),
                ('buyer_disputed', models.BooleanField(default=False)),
                ('seller_disputed', models.BooleanField(default=False)),
                ('escrow_complete', models.BooleanField(default=False)),
                ('seller_paid', models.BooleanField(default=False)),
                ('platform_paid', models.BooleanField(default=False)),
                ('sale_finalized', models.BooleanField(default=False)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bids.ItemBid')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='items.Item')),
            ],
        ),
    ]
