# Generated by Django 2.2.8 on 2020-01-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200107_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsale',
            name='sale_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
